apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: resource-profiler
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: resource-profiling
  labels:
    app: resource-profiler
spec:
  source:
    type: Git
    git:
      uri: https://github.com/mcharanrm/resource-profiling
  strategy:
    type: Docker      
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: resource-profiler:latest
  serviceAccount: builder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiling-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-profiler
  template:
    metadata:
      labels:
        app: resource-profiler
    spec:
      containers:
      - name: profiler
        image: 'image-registry.openshift-image-registry.svc:5000/ocp-ai-rp/resource-profiler:latest'
      resources:
        requests:
          memory: "1024Mi"
          cpu: "1000m"
        limits:
          memory: "2048Mi"
          cpu: "1200m"